src/miniproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home_view'),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import (
    post_review_create_list_view,
    like_unlike_post_view,
    create_post_view,
    create_review_view,
    like_unlike_review_view,
    delete_post_view,
    delete_review_view,
    search_book_list_view,
    show_book_view,
    )

app_name = 'posts'

urlpatterns = [
    path('',post_review_create_list_view,name='main-post-view'),
    path('add_post/',create_post_view,name='create-post-view'),
    path('post_liked/',like_unlike_post_view,name='like-post-view'),
    path('delete_post/',delete_post_view,name='delete-post-view'),
    path('add_review/',create_review_view,name='create-review-view'),
    path('review_liked/',like_unlike_review_view,name='like-review-view'),
    path('delete_review/',delete_review_view,name='delete-review-view'),
    path('search_book/',search_book_list_view,name='search-book'),
    path('book/<str:id>/',show_book_view,name='show-book'),
    #path('show_profile/',show_profile_from_post,name='show-profile-from-post')
]

src/profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,PasswordResetCompleteView,
    PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView
)

app_name = 'profiles'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='accounts/main_login.html'),name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/main_logout.html'),name="logout"),
    path('signup/', views.register,name="register"),
    path('myprofile/',views.my_profile_view,name='my-profile-view' ),
    path('followers/',views.my_followers_list_view,name='my-follower-list-view'),
    path('youfollow/',views.you_follow_list_view,name='you-follow-list-view'),
    path('all_users_view/',views.all_users_list_view,name='all-users-list-view'),
    path('profile_view/',views.view_profile_view,name='profile-view'),
    path('specific_profile_view/',views.specific_profile_view,name='specific-profile-view'),
    path('follow_unfollow/',views.follow_unfollow_view,name='follow-unfollow-view'),
]

#http://127.0.0.1:8000/profiles ->main url.py
#http://127.0.0.1:8000/profiles/myprofile ->main url.py

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=200,blank=True)
    last_name = models.CharField(max_length=200,blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio",max_length=300)
    email = models.EmailField(max_length=200,blank=True)
    country = models.CharField(max_length=200,blank=True)
    avatar = models.ImageField(default='avatar.png',upload_to='avatars/')
    #install pillow
    #createmedia_root
    #find avatar.png
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    you_follow = models.ManyToManyField(User, blank=True, related_name='you_follow')
    slug = models.SlugField(unique=True,blank=True)
    exp = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_followers(self):
        return self.followers.all()

    def get_followers_no(self):
        return self.followers.all().count()

    def get_you_follow(self):
        return self.you_follow.all()

    def get_you_follow_no(self):
        return self.you_follow.all().count()

    def get_posts_num(self):
        return self.posts.all().count()

    def get_likes_num(self):
        likes = self.post_like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked+=1
        return total_liked

    def get_likes_received_post_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def get_likes_received_review_no(self):
        reviews = self.reviews.all()
        total_liked = 0
        for item in reviews:
            total_liked += item.liked.all().count()
        return total_liked

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name :
            to_slug = slugify(str(self.first_name)+str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else :
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'follow'),
    ('send', 'unfollow')
)

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8,choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def _str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

src/profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name','last_name','bio','avatar')

src/profiles/views.py
from django.shortcuts import render,redirect
from .models import Profile,Relationship
from posts.models import Review
from posts.ML import predict as pr
from .forms import ProfileModelForm
from django.contrib.auth.models import User

# Create your views here.
def my_profile_view(request):
    obj = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None,request.FILES or None,instance=obj)
    confirm = False
    if request.method =='POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'obj': obj,
        'form':form,
        'confirm':confirm
    }
    return render(request,'profiles/myprofile.html',context)

def my_followers_list_view(request):
    user = request.user
    profile = Profile.objects.get(user=request.user)
    followers = profile.get_followers()
    content = {
        'obj':followers,
        'profile':profile,
    }
    return render(request,'profiles/followers.html',content)

def you_follow_list_view(request):
    user = request.user
    profile = Profile.objects.get(user=request.user)
    you_follow = profile.get_you_follow()
    content = {
        'obj':you_follow,
        'profile':profile,
    }
    return render(request,'profiles/you_follow.html',content)

def all_users_list_view(request):
    user=  request.user
    notfound = True
    searched = False
    all_users = Profile.objects.all()
    if request.method=='POST':
        searched = True
        user_name = request.POST.get('user')
        for profile in all_users:
            if user_name in str(profile.user).lower():
                notfound = False
            elif user_name in profile.slug.lower():
                notfound = False
            if not notfound:
                user_content = {
                    'obj':profile,
                    'profile':Profile.objects.get(user=request.user),
                }
                return render(request,'profiles/profile_view.html',user_content)

    content = {
        'profiles':all_users,
        'user_found':notfound,
        'searched':searched,
    }
    return render(request, 'profiles/users_list.html',content)

def view_profile_view(request):
    user = request.user
    if request.method=='POST':
        id = request.POST.get('profile_id')
        profile = Profile.objects.get(user=User.objects.get(username=id))
        content = {
            'obj':profile,
            'profile':Profile.objects.get(user=request.user),
        }
        return render(request,'profiles/profile_view.html',content)
    else:
        return render(request,'profiles/profile_view.html')

def specific_profile_view(request):
    user = request.user
    if request.method=='POST':
        id = request.POST.get('profile_id')
        profile = Profile.objects.get(slug=id)
        content = {
            'obj':profile,
            'profile':Profile.objects.get(user=request.user),
        }
        return render(request,'profiles/profile_view.html',content)

def register(request):
    args={
        'uname':'',
        'u_already_exists':False,
    }
    if request.method=='POST':
        existing = True
        username = request.POST.get('username')
        password1 = request.POST.get('password_1')
        password2 = request.POST.get('password_2')

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            existing = False

        args={
            'uname':username,
            'u_already_exists':existing,
        }
        if password1!=password2:
            return render(request,'accounts/main_signup.html',args)

        if existing:
            return render(request, 'accounts/main_signup.html',args)

        User.objects.create_user(username=username,password=password1)
            #return render(request,'accounts/signup.html',args)
        return redirect('profiles:login')
    else :
        return render(request,'accounts/main_signup.html',args)

def follow_unfollow_view(request):
    user = request.user
    if request.method=='POST':
        p_id = request.POST.get('profile_id')
        from_profile = Profile.objects.get(user=user)
        to_profile = Profile.objects.get(id=p_id)
        if to_profile in from_profile.get_you_follow():
            status='unfollow'
        else:
            status='follow'

        relation, created = Relationship.objects.get_or_create(sender=from_profile,receiver=to_profile,status=status)
        if not created:
            from_profile.you_follow.remove(to_profile.user)
            to_profile.followers.remove(from_profile.user)
            Relationship.objects.filter(sender=from_profile,receiver=to_profile).delete()
            from_profile.save()
            to_profile.save()
        else:
            relation.save()

        reviews = Review.objects.all()
        for re in reviews:
            if to_profile.user==re.user.user:
                re.expertivity = pr.calc_expertivity(to_profile.get_followers_no(),to_profile.get_likes_received_review_no())
                re.save()

        return redirect('profiles:my-profile-view')

src/profiles/templates/profiles/followers.html
{% extends 'basic.html' %}

{% block title %}
Followers
{% endblock %}

{% block content %}
	<div style="margin-left: 140px;margin-right: 0;">
	<h1 style="margin: 5px;padding: 0;width: 100%"><i class="fas fa-user-friends"></i> Followers</h1>
	</div>
	<table class=" f_table table ">
		<tbody>
			{% for follower in obj %}
			<div class="follower_username">
			<tr>
				<td style="width:50%;"><center>{{follower}}</center></td>
			</div>
			<form action="{% url 'profiles:profile-view' %}" method="post" style="width:30%;">
			  {% csrf_token %}
			  <td style="width:50%;">
			  	<center>
			  <input type="hidden" name="profile_id" value={{follower}}>
			  <button type="submit" name="button">View Profile</button>
			</center>
			</td>
			</form>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}

src/profiles/templates/profiles/myprofile.html
{% extends 'basic.html' %}

{% block title %}
My Profile
{% endblock %}

{% block content %}


<div class="profile">
  {% if confirm %}
  <div class="green_msg">Updated!</div>
  {% endif %}
  <i><h2>{{obj.user}}</h2></i>
  <div class="ui grid">
  <div class="row">
    <div class="profile_image">
      <img class="ui medium rounded image" src="{{obj.avatar.url}}" style="width:130px;height:130px;">
      <div class="row mt-5">
        <a href="#update_prof">
      <button class='upd_btn' id='modal-btn' onclick="Update_btn_click()">Update</button>
    </a>
      </div>
    </div>
    <div class="profile_image_side">
      <table class="table">
        <tbody>
          <tr>
            <th style='width:250px;'>Attribute</th>
            <th>Data</th>
          </tr>
          <tr>
            <td>Username</td>
            <td>{{obj.user}}</td>
          </tr>
          <tr>
            <td>Firstname</td>
            <td>{{obj.first_name}}</td>
          </tr>
          <tr>
            <td>Lastname</td>
            <td>{{obj.last_name}}</td>
          </tr>
          <tr>
            <td>Bio</td>
            <td>{{obj.bio}}</td>
          </tr>
          <tr>
            <td>Followers</td>
            <td>
              {% if obj.get_followers_no %}
              {{obj.get_followers_no}}
              <a href="{% url 'profiles:my-follower-list-view' %}"><i>(View)</i></a>
              {% else %}
              {{obj.get_followers_no}}
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Following</td>
            <td>
              {% if obj.get_you_follow_no %}
              {{obj.get_you_follow_no}}
              <a href="{% url 'profiles:you-follow-list-view' %}"><i>(View)</i></a>
              {% else %}
              {{obj.get_you_follow_no}}
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Number of posts</td>
            <td>{{obj.get_posts_num}}</td>
          </tr>
          <tr>
            <td>Number of likes given</td>
            <td>{{obj.get_likes_num}}</td>
          </tr>
          <tr>
            <td>Likes received to my post</td>
            <td>{{obj.get_likes_received_post_no}}</td>
          </tr>
          <tr>
            <td>Likes received to my reviews</td>
            <td>{{obj.get_likes_received_review_no}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>
<hr>
<!-- MODAL -->
<div class="updateform" id="update" style="margin-left: 21px;overflow: hidden;">
  <i class="close icon"></i>
  <div class="header" id="update_prof" style="font-size: 40px;font-weight: bold;">
    Update :
  </div>
  <div class="image content">
    <div class="ui medium image" >
      <img src="{{obj.avatar.url}}" style="width:130px;height:130px;">
    </div>
    <div class="description">
      <div class="header" style="font-size: 25px;font-weight: bold;">Provide some additional/newest info about you </div>
      <form action="" method="POST" class="info_form" enctype='multipart/form-data' style="padding: 15px;">
        {% csrf_token %}
        {{form.as_p}}
  <div class="actions" style="">
    <button type='submit' class="ui positive right labeled icon button" style="margin:10px;font-size: 31px;">
      Update
      <i class="checkmark icon"></i>
    </button>
  </div>
        </form>
      </div>
    </div>

</div>


{% endblock content %}

src/profiles/templates/profiles/profile_view.html
{% extends 'basic.html' %}

{% block title %}
Profile
{% endblock %}

{% block content %}

<div class="profile">
  <h3 style="width:15%;display: inline-flex;">{{obj.user}}</h3>
  <form action="{% url 'profiles:follow-unfollow-view' %}" method="post" style="display: inline-flex;">
    {% csrf_token %}
    <input type="hidden" name="profile_id" value={{obj.pk}}>
    <button type="submit" name="button" style="font-size: 25px;">
      {% if obj.user in profile.get_you_follow %}
      Unfollow
      {% else %}
      Follow
      {% endif %}
    </button>
  </form>
  <div class="ui grid">
  <div class="row">
    <div class="six wide column">
      <img class="ui medium rounded image" src="{{obj.avatar.url}}" style="width:130px;height:130px;">
    </div>
    <div cstyle="width: 50%;margin-left: 15%;display: inline-flex;">
      <table class="table" style="display: inline-flex;margin-top: 10px;height: 700px;">
        <tbody style="width:50%;">
          <tr>
            <th style="width: 20%;">Attribute</th>
            <th style="width: 20%;">Data</th>
          </tr>
          <tr>
            <td>username</td>
            <td>{{obj.user}}</td>
          </tr>
          <tr>
            <td>firstname</td>
            <td>{{obj.first_name}}</td>
          </tr>
          <tr>
            <td>lastname</td>
            <td>{{obj.last_name}}</td>
          </tr>
          <tr>
            <td>Bio</td>
            <td>{{obj.bio}}</td>
          </tr>
          <tr>
            <td>Number of followers</td>
            <td>{{obj.get_followers_no}}</td>
          </tr>
          <tr>
            <td>Followers</td>
            <td>
              <ul>
              {% for follower in obj.get_followers %}
              <li>{{follower}}</li>
              {% endfor %}
              </ul>
            </td>
          </tr>
          <tr>
            <td>You Follow</td>
            <td>{{obj.get_you_follow_no}}</td>
          </tr>
          {% if obj.get_you_follow_no %}
          <tr>
            <td>Following</td>
            <td>
              <ul>
              {% for following in obj.get_you_follow %}
              <li>{{following}}</li>
              {% endfor %}
              </ul>
            </td>
          </tr>
          {% endif %}
          <tr>
            <td>Number of posts</td>
            <td>{{obj.get_posts_num}}</td>
          </tr>
          <tr>
            <td>Number of likes given</td>
            <td>{{obj.get_likes_num}}</td>
          </tr>
          <tr>
            <td>Number of likes received to his/her post</td>
            <td>{{obj.get_likes_received_post_no}}</td>
          </tr>
          <tr>
            <td>Number of likes received to his/her reviews</td>
            <td>{{obj.get_likes_received_review_no}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>


{% endblock content %}

src/profiles/templates/profiles/users_list.html
{% extends 'basic.html' %}

{% block title %}
All Users
{% endblock title %}

{% block content %}
  {% if searched %}
    {% if user_found %}
      <h1 style="color:green;">User Not Found!</h1>
    {% endif %}
  {% endif %}
  <div style="margin-left: 140px;margin-right: 0;">
    <h1 style="margin: 5px;padding: 0;width: 100%"><i class="fas fa-user-friends"></i>All Users</h1>
    <form action="{% url 'profiles:all-users-list-view' %}" method="post">
      {% csrf_token %}
      <div class="Search">
        <input type="text" placeholder="Search for User" style="padding: 3px;" name="user">
        <button type="submit" class="btns"><i class="fa fa-search" style="color:black;"></i></button>
      </div>
    </form>
  </div>
  <table class=" f_table table ">
    <tbody>
      {% for user in profiles %}
      <div class="follower_username">
      <tr>
      	<td style="width:50%;"><center>{{user.user}}</center></td>
      </div>
      <form action="{% url 'profiles:specific-profile-view' %}" method="post">
        {% csrf_token %}
        <td style="width:50%;">
        	<center>
        <input type="hidden" name="profile_id" value={{user.slug}}>
        <button type="submit" name="button">View Profile</button>
      </center>
      </td>
      </form>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

src/profiles/templates/profiles/you_follow.html
{% extends 'basic.html' %}

{% block title %}
You follow
{% endblock title %}

{% block content %}
	<div style="margin-left: 140px;margin-right: 0;">
	<h1 style="margin: 5px;padding: 0;width: 100%"><i class="fas fa-user-friends"></i> Following</h1>
	</div>
	<table class=" f_table table ">
		<tbody>
			{% for you_follow in obj %}
			<div class="follower_username">
			<tr>
				<td style="width:50%;"><center>{{you_follow}}</center></td>
			</div>
			<form action="{% url 'profiles:profile-view' %}" method="post">
			  {% csrf_token %}
			  <td style="width:50%;">
			  	<center>
			  <input type="hidden" name="profile_id" value={{you_follow}}>
			  <button type="submit" name="button">View Profile</button>
			</center>
			</td>
			</form>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}