src/miniproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home_view'),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import (
    post_review_create_list_view,
    like_unlike_post_view,
    create_post_view,
    create_review_view,
    like_unlike_review_view,
    delete_post_view,
    delete_review_view,
    search_book_list_view,
    show_book_view,
    )

app_name = 'posts'

urlpatterns = [
    path('',post_review_create_list_view,name='main-post-view'),
    path('add_post/',create_post_view,name='create-post-view'),
    path('post_liked/',like_unlike_post_view,name='like-post-view'),
    path('delete_post/',delete_post_view,name='delete-post-view'),
    path('add_review/',create_review_view,name='create-review-view'),
    path('review_liked/',like_unlike_review_view,name='like-review-view'),
    path('delete_review/',delete_review_view,name='delete-review-view'),
    path('search_book/',search_book_list_view,name='search-book'),
    path('book/<str:id>/',show_book_view,name='show-book'),
    #path('show_profile/',show_profile_from_post,name='show-profile-from-post')
]

src/profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,PasswordResetCompleteView,
    PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView
)

app_name = 'profiles'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='accounts/main_login.html'),name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/main_logout.html'),name="logout"),
    path('signup/', views.register,name="register"),
    path('myprofile/',views.my_profile_view,name='my-profile-view' ),
    path('followers/',views.my_followers_list_view,name='my-follower-list-view'),
    path('youfollow/',views.you_follow_list_view,name='you-follow-list-view'),
    path('all_users_view/',views.all_users_list_view,name='all-users-list-view'),
    path('profile_view/',views.view_profile_view,name='profile-view'),
    path('specific_profile_view/',views.specific_profile_view,name='specific-profile-view'),
    path('follow_unfollow/',views.follow_unfollow_view,name='follow-unfollow-view'),
]

#http://127.0.0.1:8000/profiles ->main url.py
#http://127.0.0.1:8000/profiles/myprofile ->main url.py

src/templates/main/footer.html
<footer>
   <div class="footer" >
     <div class="foot">
     <h4>Links</h4>
     <a href="/" class="links">Home</a>
            {% if user.is_authenticated %}
            <a href="{% url 'posts:main-post-view' %}" class="links">Posts</a>
            <a href="{% url 'profiles:my-profile-view' %}" class="links">My Profile</a>
            {% endif %}
   </div>
   <div style="float:right" class="fa">
     <h4>Contact Us</h4>
     <a href="#" class="fa fa-facebook"></a>
     <a href="#" class="fa fa-twitter"></a>
     <a href="#" class="fa fa-linkedin"></a>
     <a href="#" class="fa fa-github"></a>
   </div>
   <hr>
   <div class="copyright">&#169 2021 IT254-Mini-Project</div>
   <div class="copyright">Authors : Shashi Rishik Naveen</div>
   </div>
 </footer>

src/templates/main/home.html
{% extends 'basic.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
  {% if not user.is_authenticated %}
  <pre>
  <h1>You are not Logged in,Want to access the website?</h1>
  <h2>If you have an account please <a href="{% url 'profiles:login' %}">login</a></h2>
  <h2>No account? No problem , just <a href="{% url 'profiles:register' %}">signup</a> in a single step</h2>
  {% else %}
  <div class="Welcome" style='margin:20px;padding:20px;'>
  <span style="font-size:300%;">Welcome {{user}}!!!<br>Happy to see you here.</span>
  </div>
  {% endif %}
  </pre>
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working from home html');
});
</script>
{% endblock scripts %}

src/templates/main/navbar.html
<div class="navbar">
    <nav>
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="/" class="links" >Home</a>
            {% if user.is_authenticated %}
            <a href="{% url 'posts:main-post-view' %}" class="links">Posts</a>
            <a href="{% url 'profiles:all-users-list-view' %}" class="links">All Users</a>
            <a href="{% url 'profiles:my-profile-view' %}" class="links">My Profile</a>
            <a href="{% url 'profiles:logout' %}" class="links">Log Out</a>
            {% endif %}
        </div>
        <div class="left_nav">
            <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
            <a href="/" class="links" style="margin-left:10px;">Home</a>
            {% if user.is_authenticated %}
            <a href="{% url 'posts:main-post-view' %}" class="links" style="margin-left:20px;">Posts</a>
            <a href="{% url 'profiles:all-users-list-view' %}" class="links">All Users</a>
            {% endif %}
        </div>
        <div class="right_nav">
          {% if user.is_authenticated %}
          <form action="{% url 'posts:search-book' %}" method="post">
            {% csrf_token %}
            <div class="Search">
              <input type="text" placeholder="Search for book" style="padding: 1px;" name="book_name">
              <button class="search_btn">Search</button>
            </div>
          </form>
            <a href="{% url 'profiles:my-profile-view' %}" class="links" style="margin-right: 20px;">My Profile</a>
        {% else %}
            <a href="{% url 'profiles:login' %}" class="links" style="margin-right: 20px;">Login</a>
            <a href="{% url 'profiles:register' %}" class="links" style="margin-right: 20px;">Sign Up</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'profiles:logout' %}" class="links">Log Out</a>
        {% endif %}
        </div>
    </nav>
</div>
<script>
    function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>