src/miniproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name='home_view'),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import (
    post_review_create_list_view,
    like_unlike_post_view,
    create_post_view,
    create_review_view,
    like_unlike_review_view,
    delete_post_view,
    delete_review_view,
    search_book_list_view,
    show_book_view,
    )

app_name = 'posts'

urlpatterns = [
    path('',post_review_create_list_view,name='main-post-view'),
    path('add_post/',create_post_view,name='create-post-view'),
    path('post_liked/',like_unlike_post_view,name='like-post-view'),
    path('delete_post/',delete_post_view,name='delete-post-view'),
    path('add_review/',create_review_view,name='create-review-view'),
    path('review_liked/',like_unlike_review_view,name='like-review-view'),
    path('delete_review/',delete_review_view,name='delete-review-view'),
    path('search_book/',search_book_list_view,name='search-book'),
    path('book/<str:id>/',show_book_view,name='show-book'),
    #path('show_profile/',show_profile_from_post,name='show-profile-from-post')
]

src/profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,PasswordResetCompleteView,
    PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView
)

app_name = 'profiles'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='accounts/main_login.html'),name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/main_logout.html'),name="logout"),
    path('signup/', views.register,name="register"),
    path('myprofile/',views.my_profile_view,name='my-profile-view' ),
    path('followers/',views.my_followers_list_view,name='my-follower-list-view'),
    path('youfollow/',views.you_follow_list_view,name='you-follow-list-view'),
    path('all_users_view/',views.all_users_list_view,name='all-users-list-view'),
    path('profile_view/',views.view_profile_view,name='profile-view'),
    path('specific_profile_view/',views.specific_profile_view,name='specific-profile-view'),
    path('follow_unfollow/',views.follow_unfollow_view,name='follow-unfollow-view'),
]

#http://127.0.0.1:8000/profiles ->main url.py
#http://127.0.0.1:8000/profiles/myprofile ->main url.py

src/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    caption = models.TextField()
    book_image = models.ImageField(default='avatar.png',upload_to='posts/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='p_likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    book_name = models.CharField(max_length=30,blank=False,default='unknown_book')
    book_author = models.CharField(max_length=30,blank=False,default='unknown_author')

    def __str__(self):
        return f"{self.book_name}-{self.book_author}"

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)

class Review(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='reviews')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='r_likes')
    expertivity = models.FloatField(default=-1.0)

    class Meta:
        ordering = ('-expertivity',)
    def __str__(self):
        return str(self.pk)

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Post_Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

class Review_Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.review}-{self.value}"

src/posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Post,Post_Like,Review,Review_Like
from profiles.models import Profile
from .ML import predict as pr
from django.http import *
from django.core.files.storage import FileSystemStorage

# Create your views here.
def post_review_create_list_view(request):
    user = request.user
    posts = Post.objects.all()
    reviews = Review.objects.all()
    profile = Profile.objects.get(user=request.user)

    context ={
        'profile':profile,
        'posts':posts,
        'reviews':reviews,
    }

    return render(request,'posts/main.html',context)


def like_unlike_post_view(request):
    user = request.user
    if request.method=='POST':
        post_id = request.POST.get('post_id1')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else :
            post_obj.liked.add(profile)

        like, created = Post_Like.objects.get_or_create(user=profile,post=post_obj)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else :
                like.value = 'Like'
        else:
            like.value='Like'

        post_obj.save()
        like.save()
        a = str(request.META.get('HTTP_REFERER'))
        a = a[22:]
        if 'posts/book/' in a:
            return HttpResponseRedirect(reverse('posts:show-book',kwargs={'id':post_obj.id}))
    return redirect('posts:main-post-view')

def create_post_view(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    if request.method=='POST':
        book_image = request.FILES['bookimage']
        fs = FileSystemStorage()
        fs.save(book_image.name, book_image)
        book_name = request.POST.get('p_name')
        book_author = request.POST.get('p_author')
        caption = request.POST.get('p_caption')

        post, created = Post.objects.get_or_create(author=profile,book_image=book_image.name,book_name=book_name,book_author=book_author,caption=caption)
        post.save()

    return redirect('posts:main-post-view')



def create_review_view(request):
    user = request.user

    if request.method=='POST':
        profile = Profile.objects.get(user=user)
        post_id = request.POST.get('post_id2')
        post_obj = Post.objects.get(id=post_id)
        review_body = request.POST.get('review_body')
        expertivity= pr.calc_expertivity(profile.get_followers_no(),profile.get_likes_received_review_no())
        review, created = Review.objects.get_or_create(user=profile,body=review_body,post_id=post_id,expertivity=expertivity)
        review.save()
        profile.exp += 2
        profile.save()

        a = str(request.META.get('HTTP_REFERER'))
        a = a[22:]
        if 'posts/book/' in a:
            return HttpResponseRedirect(reverse('posts:show-book',kwargs={'id':post_obj.id}))

    return redirect('posts:main-post-view')

def like_unlike_review_view(request):
    user = request.user
    if request.method=='POST':
        post_id = request.POST.get('post_id3')
        review_id = request.POST.get('review_id')
        post_obj = Post.objects.get(id=post_id)
        review_obj = Review.objects.get(id=review_id)
        profile = Profile.objects.get(user=user)
        review_author = Profile.objects.get(id=review_obj.user.id)

        if profile in review_obj.liked.all():
            review_obj.liked.remove(profile)
        else :
            review_obj.liked.add(profile)

        like, created = Review_Like.objects.get_or_create(user=profile,review=review_obj)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
                review_author.exp -= 1
            else:
                like.value='Like'
                review_author.exp += 1
        else:
            like.value='Like'
            review_author.exp += 1

        like.save()
        review_obj.save()
        review_author.save()
        review_obj.expertivity = pr.calc_expertivity(review_author.get_followers_no(),review_author.get_likes_received_review_no())
        review_obj.save()
        a = str(request.META.get('HTTP_REFERER'))
        a = a[22:]

        if 'posts/book/' in a:
            return HttpResponseRedirect(reverse('posts:show-book',kwargs={'id':post_obj.id}))
    return redirect('posts:main-post-view')

def delete_post_view(request):
    user = request.user
    if request.method=='POST':
        post_id = request.POST.get('post_id4')
        posts = Post.objects.all()
        if not post_id:
            return redirect('posts:main-post-view')
        post_obj = Post.objects.get(id=post_id)

        if post_obj in posts:
            Post.objects.filter(id=post_id).delete()

    return redirect('posts:main-post-view')

def delete_review_view(request):
    user = request.user
    if request.method=='POST':
        post_id = request.POST.get('post_id')
        review_id = request.POST.get('review_id')
        reviews = Review.objects.all()


        if not post_id:
            return redirect('posts:main-post-view')
        elif not review_id:
            return redirect('post:main-post-view')

        review_obj = Review.objects.get(id=review_id)
        re_auth = Profile.objects.get(id=review_obj.user.id)

        if review_obj in reviews:
            re_auth.exp = re_auth.exp -2
            Review.objects.filter(id=review_id).delete()

    return redirect('posts:main-post-view')

def show_book_view(request, id):
    book = Post.objects.get(id=id)
    reviews = Review.objects.all()
    profile = Profile.objects.get(user=request.user)
    context ={
        'profile':profile,
        'posts':book,
        'reviews':reviews,
    }
    return render(request,'posts/search_book.html',context)

def search_book_list_view(request):
    user = request.user
    if request.method=='POST':
        flag=0
        book_name = request.POST.get('book_name')
        all_books = Post.objects.all()
        for book in all_books:
            if book_name in book.book_name.lower():
                book_found = book
                flag=1
        reviews = Review.objects.all()
        profile = Profile.objects.get(user=request.user)

        if flag:
            context ={
                'profile':profile,
                'posts':book_found,
                'reviews':reviews,
            }

            return HttpResponseRedirect(reverse('posts:show-book',kwargs={'id':book_found.id}))
            #return render(request,'posts/search_book.html',context)
        else :
            message = "book "+ book_name +" not found"
            context ={
                'message':message,
            }
            return render(request,'notfound.html',context)

src/posts/templates/posts/main.html
{% extends 'basic.html' %}
{% load static %}

{% block title %}
all_books
{% endblock title %}

{% block content %}
{% if profile.user.is_superuser %}
<div class="post_a_new_book">
  <h1>Post a new Book</h1>
</div>
<div class="newpost">
  <form action="{% url 'posts:create-post-view' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="newpost_indiv">
        <label for="p_caption">Caption</label>
        <input type="textarea" name="p_caption"><br>
      </div>
      <div class="newpost_indiv">
        <label for="p_img">Image</label>
        <input type="file" name="bookimage"><br>
      </div>
      <div class="newpost_indiv">
        <label for="p_name">Book title</label>
        <input type="text" name="p_name"><br>
      </div>
      <div class="newpost_indiv">
        <label for="p_author">Author</label>
        <input type="text" name="p_author"><br>
      </div>
      <div class="newpost_indiv">
        <button type="submit" class="newpost_btn"><div class='btn' style='font-size: 120%;'>Post</div></button><br>
      </div>
  </form>
</div>
{% endif %}

<h1 style=";">Books & Reviews</h1>
{% for obj1 in posts %}
<div class="post_review">
  <div class="post">
  <div class="post_indiv">
    <div class="book_name" style="padding-bottom: 10px">{{obj1.book_name}}</div>

    <img src="{{obj1.book_image.url}}" style="width:110px;height:140px;">

  </div>
  <form action="{% url 'posts:like-post-view' %}" method="POST">
    {% csrf_token %}
    <div class="post_indiv">
      <input type="hidden" name="post_id1" value={{obj1.id}}>
      <button type="submit">
          <div class='btn'>
            {% if profile not in obj1.liked.all %}
            <i class="fa fa-thumbs-up fa_change"></i>
            {% else %}
            <i class="fa fa-thumbs-down fa_change"></i>
            {% endif %}
          </div>
       </button>
       <span class="likes">{{obj1.liked.all.count}}</span>
     </div>
  </form>
  <div class="post_indiv">
      {% if profile.user.is_superuser %}
    <form action="{% url 'posts:delete-post-view' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="post_id4" value={{obj1.id}}>
      <button type="submit">
        <div class='btn'>Delete book</div>
      </button>
    </form>
      {% endif %}
  </div>
  </div>

  {% for obj2 in reviews %}
  <div class="reviews">
    {% ifequal obj2.post_id obj1.id %}
    <div class="review_text">
      <form action="{% url 'profiles:specific-profile-view' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="profile_id" value={{obj2.user.slug}}>
        <button style="border:none;font-size:18px;" onclick="submit"><b>{{obj2.user.user}}</b></button>
      </form>
      <p style="padding-left: 20px;">{{obj2.body}}</p>
    </div>
    <form action="{% url 'posts:like-review-view' %}" method="POST" class="post_indiv">
      {% csrf_token %}
      <input type="hidden" name="post_id3" value={{obj1.id}}>
      <input type="hidden" name="review_id" value={{obj2.id}}>
      <button type="submit">
        <div class='btn'>
            {% if profile not in obj2.liked.all %}
            <i class="fa fa-thumbs-up fa_change" style="font-size: 25px;padding-left: 20px;"></i>
            {% else %}
            <i class="fa fa-thumbs-down fa_change" style="font-size: 25px;padding-left: 20px;"></i>
            {% endif %}
        </div>
       </button>
       <span class="likes">{{obj2.liked.all.count}}</span>
    </form>

    {% ifequal profile.slug obj2.user.slug %}
    <form action="{% url 'posts:delete-review-view' %}" method="POST" class="post_indiv">
      {% csrf_token %}
      <input type="hidden" name="post_id" value={{obj1.id}}>
      <input type="hidden" name="review_id" value={{obj2.id}}>
      <button type="submit">
        <div class='btn'>Delete Review</div>
      </button>
    </form>
    {% endifequal %}

    {% endifequal %}
  </div>
  {% endfor %}

  <div class="post_new_review">
    <form action="{% url 'posts:create-review-view' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="review_body" placeholder="Add review!!!" style="padding:5px;border-radius:5%;">
      <input type="hidden" name="post_id2" value={{obj1.id}}>
      <button type="submit">
        <div class='btn' style="padding:3px;">Post review</div>
      </button>
    </form>
  </div>
</div>
<div style="margin: 2%;"></div>
{% endfor %}
{% endblock content %}

src/posts/templates/posts/search_book.html
{% extends 'basic.html' %}
{% load static %}

{% block title %}
searched-book
{% endblock title %}

{% block content %}

<h1 style=";">Book & Reviews</h1>
<div class="post_review">
  <div class="post">
    <div class="post_indiv">
      <div class="book_name">{{posts.book_name}}</div>
    </div>
    <form action="{% url 'posts:like-post-view' %}" method="POST">
      {% csrf_token %}
      <div class="post_indiv">
        <input type="hidden" name="post_id1" value={{posts.id}}>
        <button type="submit">
          <div class='btn'>
            {% if profile not in posts.liked.all %}
              <i class="fa fa-thumbs-up fa_change"></i>
            {% else %}
              <i class="fa fa-thumbs-down fa_change"></i>
            {% endif %}
          </div>
        </button>
        <span class="likes">{{posts.liked.all.count}}</span>
      </div>
    </form>
    <div class="post_indiv">
      {% if profile.user.is_superuser %}
      <form action="{% url 'posts:delete-post-view' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="post_id4" value={{posts.id}}>
        <button type="submit">
          <div class='btn'>Delete book</div>
        </button>
      </form>
      {% endif %}
    </div>
  </div>

  {% for obj2 in reviews %}
    <div class="reviews">
      {% ifequal obj2.post_id posts.id %}
        <div class="review_text">
          <form action="{% url 'profiles:specific-profile-view' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_id" value={{obj2.user.slug}}>
            <button style="border:none;font-size:18px;" onclick="submit">
              <b>{{obj2.user.user}}</b>
            </button>
          </form>
          <p style="padding-left: 20px;">{{obj2.body}}</p>
        </div>
        <form action="{% url 'posts:like-review-view' %}" method="POST" class="post_indiv">
          {% csrf_token %}
          <input type="hidden" name="post_id3" value={{posts.id}}>
          <input type="hidden" name="review_id" value={{obj2.id}}>
          <button type="submit">
            <div class='btn'>
              {% if profile not in obj2.liked.all %}
                <i class="fa fa-thumbs-up fa_change" style="font-size: 25px;padding-left: 20px;"></i>
              {% else %}
                <i class="fa fa-thumbs-down fa_change" style="font-size: 25px;padding-left: 20px;"></i>
              {% endif %}
            </div>
          </button>
           <span class="likes"> {{obj2.liked.all.count}}</span>
        </form>

        {% ifequal profile.slug obj2.user.slug %}
        <form action="{% url 'posts:delete-review-view' %}" method="POST" class="post_indiv">
          {% csrf_token %}
          <input type="hidden" name="post_id" value={{posts.id}}>
          <input type="hidden" name="review_id" value={{obj2.id}}>
          <button type="submit">
            <div class='btn'>Delete Review</div>
          </button>
        </form>
        {% endifequal %}
      {% endifequal %}
    </div>
  {% endfor %}

  <div class="post_new_review">
    <form action="{% url 'posts:create-review-view' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="review_body" placeholder="Add review!!!" style="padding:5px;border-radius:5%;">
      <input type="hidden" name="post_id2" value={{posts.id}}>
      <button type="submit">
        <div class='btn' style="padding:3px;">Post review</div>
      </button>
    </form>
  </div>
</div>
<div style="margin: 2%;"></div>

{% endblock content %}